import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactQueryProvider } from "@/lib/react-query-provider";
import { Navbar } from "@/components/layout/navbar";
import "../globals.css";
import { NextAuthProvider } from "../providers/session-provider";
import Footer from "@/components/layout/footer";
// import { GlobalLoadingProgress } from "@/components/global-loading-progress";
import { LoadingProgress } from "./components/loading-progress";
import { RouteChangeHandler } from "./components/RouteChangeHandler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 relative">
        {/* <GlobalLoadingProgress /> */}
        <LoadingProgress />
        <RouteChangeHandler />
        <NextAuthProvider>
          <ReactQueryProvider>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </ReactQueryProvider>
        </NextAuthProvider>
        
      </body>
    </html>
  );
}
