import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactQueryProvider } from "@/lib/react-query-provider";
import { Navbar } from "@/components/layout/navbar";
import "../globals.css";
import { NextAuthProvider } from "../providers/session-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body> */}
      <body className="bg-gray-50 text-gray-900">
        <NextAuthProvider>
          <ReactQueryProvider>
            <Navbar />
            <main>{children}</main>
          </ReactQueryProvider>
        </NextAuthProvider>
        
      </body>
    </html>
  );
}
