import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactQueryProvider } from "@/lib/react-query-provider";
import { Navbar } from "@/components/layout/navbar";
import "./../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SignupLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body> */}
      <body className="bg-gray-50 text-gray-900">
        <ReactQueryProvider>
          <h1>This Is Auth Layout</h1>
          <main>{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
