import type { Metadata } from "next";
import { ReactQueryProvider } from "@/lib/react-query-provider";
import "./../globals.css";
import { NextAuthProvider } from "../providers/session-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SignupLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className="bg-gray-50 text-gray-900 flex min-h-screen items-center justify-center">
        <NextAuthProvider>
          <ReactQueryProvider>
            {children}
          </ReactQueryProvider>
        </NextAuthProvider>        
        
      </body>
    </html>
  );
}
